apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: default
  labels:
    component: elk
    role: elasticsearch
spec:
  selector:
    component: elk
    role: elasticsearch
  ports:
  - name: one
    port: 9200
    targetPort: 9200
    protocol: TCP
  - name: two
    port: 9300
    targetPort: 9300
    protocol: TCP

