apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: default
  labels:
    component: elk
    role: logstash
spec:
  selector:
    component: elk
    role: logstash
  ports:
  - name: logstash
    port: 5000
    protocol: TCP
